output DP-1 resolution 1920x1080@60Hz position 0,0
output DP-2 resolution 2560x1440@144Hz position 1920,0
output HDMI-A-1 resolution 1920x1080@60Hz position 4480,0

set $bg_path "$HOME/Pictures/tokyo_night.png"
output HDMI-A-1 bg $bg_path stretch
output DP-2 bg $bg_path stretch
output DP-1 bg $bg_path stretch

