# App launcher -> wmenu-run is not available in ubuntu 24
unbindsym $mod+d
bindsym $mod+d exec rofi -show drun -config ~/.config/rofi/run.rasi -show-icons -icon-theme Yaru

# Display config
exec --no-startup-id swaybg --image ~/Bilder/tokyo_night.jpeg --mode fill

output eDP-1 {
    mode 2880x1800@120.000Hz
    pos 0 0
    scale 1.5
    scale_filter linear
}

# Büro arbeitsplatz
output "Samsung Electric Company C27F390 H4ZM107934" {
    mode 1920x1080@60.000Hz
    pos 1920 0
    scale 1
    scale_filter nearest
}
output "Samsung Electric Company C27F390 H4ZKC10953" {
    mode 1920x1080@60.000Hz
    pos 3840 0
    scale 1
    scale_filter nearest
}
output "Samsung Electric Company C27F390 HTHK201889" {
    mode 1920x1080@60.000Hz
    pos 5760 0
    scale 1
    scale_filter nearest
}

# Autostart apps
assign [app_id="jetbrains-phpstorm"] workspace number 1

assign [app_id="^firefox$"] workspace number 2
exec gtk-launch firefox

assign [app_id="firefox-nightly"] workspace number 10
exec gtk-launch firefox-nightly
assign [app_id="1password"] workspace number 10
exec gtk-launch 1password
assign [class="Spotify"] workspace number 10
exec gtk-launch spotify

